import Head from 'next/head'
import Link from 'next/link'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <h1>Welcome</h1>

      <Link href='/cats' passHref>
        <a href='replaced'>View Cats</a>
      </Link>
    </div>
  )
}
