import Head from 'next/head'
import { useEffect, useState } from 'react'
import getCats from '../firestore/reads'
import Cat from '../types/cat'

export default function Home() {
  const [cats, setCats] = useState<Cat[]>([])

  useEffect(() => {
    getCats().then(setCats)
  }, [])

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      {cats.map((cat) => (
        <h5 key={cat.id}>{cat.name}</h5>
      ))}
    </div>
  )
}
